deathMessages = [
    ' took the L.',
    ' fell out of the world.',
    ' committed toaster bath.',
    ' decided to commit die.',
    ' got ora ora\'d to death.',
    '\'s soul left their body.',
    ' was put through a pepper grinder.',
    ' died in a hole.',
    ' procrastinated on their homework.',
    ' forgot to turn off the oven.',
    ' went skydiving attached to a fridge.',
    ' pressed alt+f4.',
    ' was struck by lightning.',
    ' forgot to study for a test.',
    ' contracted COVID-19.',
    ' was crushed by an anvil.',
    ' tried to swim in lava.',
    ' dug straight down.',
    ' stayed up too late watching anime.',
    ' donated their life savings to Pokimane.',
    ' misspelled among us.',
    ' needs to GIT GUD!',
    ' gooottttttt dunked on!!!',
    ' has committed neck rope.',
    ' was sent to the gulag.',
    ' went to Brazil.',
    ' did not juju on that beat.',
    ' got deported.',
    ' committed tax evasion.',
    ' stepped on some legoes.',
    ' did not expect the spanish inquisition.',
    ' ordered pineapple on pizza.',
    ' read 177013.',
    ' fell for it! THUNDER CROSS SPLIT ATTACKKKKKKK!!!!!',
    ' got stick bugged lol',
    ' is no stranger to love. They know the rules, and so do I. A full commitments what I\'m thinking of. They wouldn\'t get this from any other guy. I just wanna tell them how I\'m feeling. Gotta make them understand...',
    ' was not winning, dad.',
    ' got DESTROYED by Ben Shapiro with FACTS and LOGIC.',
    ' didn\'t find the lamb sauce.',
    ' got fucking wrecked lmao',
    ' broke their back from _CARRYING_ everyone else in the game.',
    ' dropped the soap.',
    ' invaded Russia in Winter.',
    ' got taken to horny jail.',
    '\'s password was hunter2.',
    ' consumed the cum chalice.',
    ' was banned from the server.',
    ' didn\'t thank the bus driver.',
    '\'s death was sponsored by RAID: Shadow Legends.',
    ' solo\'d Baron.',
    ' got cancelled.',
    ' tried to outlive the queen.',
    ' shot the archduke of Austria.',
    ' committed seppuku.',
    '\'s free trial of life expired.',
    ' hit a kaizo block.',
    ' watched Boku no Pico.',
    ' is bad and should feel bad.',
    ' lost the game.',
    ' divided by 0.',
    ' was the imposter! Or were they?',
    '\'s team let them down.',
    ' attended a Trump rally with a BLM sign.',
    ' ーはすでに死んでいた.',
    ' 死了。',
    ' found Jesus.',
    ' was not HALAL.',
    ' tried to keep up with everyone\'s requests.',
    ' tried to make a Discord Bot.',
    ' fell into the wrong vat of acid.',
    ' was reincarnated into another world.',
    ' can return by dea-',
    ' chose to bring a useless goddess in a fantasy world.',
    ' drank gamer girl bath water.',
    ' tried to sleep in the nether.',
    '! The secret to DIO\'s stand is-',
    ' got donuted.',
    ' did not realize... KILLER QUEEN HAS ALREADY TOUCHED THAT DOORKNOB.',
    '\'s head was crushed by an ambulance.',
    ' sucks at this game.',
    ' learned of KILLER QUEEN\'S third ability: BITES ZA DUSTO'
]

endMessages = [
    'Game has ended! GGWP.',
    'And they all lived horribly afterwards.',
    'Good game, poorly played.',
    'Game ended. Easy peasy, lemon squeezy.',
    'Game over. Play again?',
    'Death is not a hunter unbeknownst to its prey, one is always aware that it lies in wait. Though life is merely a journey to the grave, it must not be undertaken without hope. Only then will a traveler’s story live on, treasured by those who bid him farewell. But alas, now my guest’s life has ended, his tale left unwritten…',
    'The game has ended. But the real treasure were the friends we made along the way.',
    'Thank you! But our princess is in another castle!',
    'You cannot give up just yet... \n Stay determined!',
    'I have successfully held taken all your families hostage. Next person who talks will have their mother\'s ribcage transformed into my personal fruit bowl.',
    '#1 Victory Royale!'
]